In [2]:
import numpy as np
import pandas as pd
import scipy.optimize as opt
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("C:\\Users\\hp\\Desktop\\ChurnData.csv")
df.head()

tenure  age  address  income  ed  employ  equip  callcard  wireless  \
0      11   33        7     136   5       5      0         1         1   
1      33   33       12      33   2       0      0         0         0   
2      23   30        9      30   1       2      0         0         0   
3      38   35        5      76   2      10      1         1         1   
4       7   35       14      80   2      15      0         1         0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...      1         0         1       1      0    1.482    3.033   
1     9.45  ...      0         0         0       0      0    2.246    3.240   
2     6.30  ...      0         0         0       1      0    1.841    3.240   
3     6.05  ...      1         1         1       1      1    1.800    3.807   
4     7.10  ...      0         0         1       1      0    1.960    3.091   

   lninc  custcat  churn  
0  4.913        4      1  
1  3.497        1      1  
2  3.401        3      0  
3  4.331        4      0  
4  4.382        3      0  

[5 rows x 28 columns]

In [5]:
df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [6]:
cdf=df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip','churn']]
cdf['churn']=cdf['churn'].astype('int')
cdf.head()

C:\Users\hp\AppData\Local\Temp/ipykernel_7488/3107781787.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cdf['churn']=cdf['churn'].astype('int')


tenure  age  address  income  ed  employ  equip  churn
0      11   33        7     136   5       5      0      1
1      33   33       12      33   2       0      0      1
2      23   30        9      30   1       2      0      0
3      38   35        5      76   2      10      1      0
4       7   35       14      80   2      15      0      0

In [7]:
cdf.shape

(200, 8)

In [8]:
x=np.asanyarray(cdf[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
x[0:5]

array([[ 11,  33,   7, 136,   5,   5,   0],
       [ 33,  33,  12,  33,   2,   0,   0],
       [ 23,  30,   9,  30,   1,   2,   0],
       [ 38,  35,   5,  76,   2,  10,   1],
       [  7,  35,  14,  80,   2,  15,   0]], dtype=int64)

In [10]:
y=np.asanyarray(cdf['churn'])
y[0:5]

array([1, 1, 0, 0, 0])

In [11]:
x=preprocessing.StandardScaler().fit(x).transform(x)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
l=LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)

In [18]:
yhat=l.predict(x_test)
yhat

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [21]:
yhat_p=l.predict_proba(x_test)
yhat

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [23]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test,yhat)

0.3888888888888889

In [25]:
from sklearn.metrics import log_loss
log_loss(y_test,yhat_p)

0.5886354989409222