In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as opt
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [8]:
df=pd.read_csv("C:\\Users\\hp\\Desktop\\clean_df (1).csv")
df.head()

Unnamed: 0  symboling  normalized-losses         make aspiration  \
0           0          3                122  alfa-romero        std   
1           1          3                122  alfa-romero        std   
2           2          1                122  alfa-romero        std   
3           3          2                164         audi        std   
4           4          2                164         audi        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   compression-ratio  horsepower  peak-rpm  city-mpg highway-mpg  price  \
0                9.0         111    5000.0        21          27  13495   
1                9.0         111    5000.0        21          27  16500   
2                9.0         154    5000.0        19          26  16500   
3               10.0         102    5500.0        24          30  13950   
4                8.0         115    5500.0        18          22  17450   

   city-L/100km horsepower-binned  diesel  gas  
0     11.190476               Low       0    1  
1     11.190476               Low       0    1  
2     12.368421            Medium       0    1  
3      9.791667               Low       0    1  
4     13.055556               Low       0    1  

[5 rows x 30 columns]

In [10]:
df.isnull().count()

Unnamed: 0           201
symboling            201
normalized-losses    201
make                 201
aspiration           201
num-of-doors         201
body-style           201
drive-wheels         201
engine-location      201
wheel-base           201
length               201
width                201
height               201
curb-weight          201
engine-type          201
num-of-cylinders     201
engine-size          201
fuel-system          201
bore                 201
stroke               201
compression-ratio    201
horsepower           201
peak-rpm             201
city-mpg             201
highway-mpg          201
price                201
city-L/100km         201
horsepower-binned    201
diesel               201
gas                  201
dtype: int64

In [11]:
df.columns

Index(['Unnamed: 0', 'symboling', 'normalized-losses', 'make', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price', 'city-L/100km', 'horsepower-binned', 'diesel',
       'gas'],
      dtype='object')

In [12]:
cdf=df[['make','body-style','num-of-cylinders','engine-size','stroke','compression-ratio','horsepower', 'peak-rpm','diesel',
       'gas']]
cdf['diesel']=cdf['diesel'].astype('int')
cdf.head()

C:\Users\hp\AppData\Local\Temp/ipykernel_1208/2625183895.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cdf['diesel']=cdf['diesel'].astype('int')


make   body-style num-of-cylinders  engine-size  stroke  \
0  alfa-romero  convertible             four          130    2.68   
1  alfa-romero  convertible             four          130    2.68   
2  alfa-romero    hatchback              six          152    3.47   
3         audi        sedan             four          109    3.40   
4         audi        sedan             five          136    3.40   

   compression-ratio  horsepower  peak-rpm  diesel  gas  
0                9.0         111    5000.0       0    1  
1                9.0         111    5000.0       0    1  
2                9.0         154    5000.0       0    1  
3               10.0         102    5500.0       0    1  
4                8.0         115    5500.0       0    1

In [13]:
cdf.shape

(201, 10)

In [15]:
x=np.asanyarray(cdf[['compression-ratio']])
x[0:5]

array([[ 9.],
       [ 9.],
       [ 9.],
       [10.],
       [ 8.]])

In [16]:
y=np.asanyarray(cdf['diesel'])
y[0:5]

array([0, 0, 0, 0, 0])

In [17]:
x=preprocessing.StandardScaler().fit(x).transform(x)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
l=LogisticRegression(C=0.01,solver='liblinear').fit(x_train,y_train)

In [20]:
yhat=l.predict(x_test)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [22]:
yhat_p=l.predict_proba(x_test)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [23]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test,yhat)

1.0

In [24]:
from sklearn.metrics import log_loss
log_loss(y_test,yhat_p)

0.4468000209887232

In [25]:
x=np.asanyarray(cdf[['engine-size']])
x[0:5]

array([[130],
       [130],
       [152],
       [109],
       [136]], dtype=int64)

In [26]:
y=np.asanyarray(cdf['gas'])
y[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [27]:
x=preprocessing.StandardScaler().fit(x).transform(x)

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
l=LogisticRegression(C=0.01,solver='liblinear').fit(x_train,y_train)

In [30]:
yhat=l.predict(x_test)
yhat

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [31]:
yhat_p=l.predict_proba(x_test)
yhat

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [32]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test,yhat)

0.926829268292683

In [33]:
from sklearn.metrics import log_loss
log_loss(y_test,yhat_p)

0.524865356315269