In [1]:
import numpy as np
import pandas as pd
import scipy.optimize as opt
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("C:\\Users\\hp\\Desktop\\teleCust1000t.csv")
df.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9      64   4       5       0       0   
1       3      11   33        1        7     136   5       5       0       0   
2       3      68   52        1       24     116   1      29       0       1   
3       2      33   33        0       12      33   2       0       0       1   
4       2      23   30        1        9      30   1       2       0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [3]:
df.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [4]:
cdf=df[['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat']]
cdf['custcat']=cdf['custcat'].astype('int')
cdf.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9      64   4       5       0       0   
1       3      11   33        1        7     136   5       5       0       0   
2       3      68   52        1       24     116   1      29       0       1   
3       2      33   33        0       12      33   2       0       0       1   
4       2      23   30        1        9      30   1       2       0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [5]:
cdf.shape

(1000, 12)

In [6]:
x=np.asanyarray(cdf[['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside']])
x[0:5]

array([[  2,  13,  44,   1,   9,  64,   4,   5,   0,   0,   2],
       [  3,  11,  33,   1,   7, 136,   5,   5,   0,   0,   6],
       [  3,  68,  52,   1,  24, 116,   1,  29,   0,   1,   2],
       [  2,  33,  33,   0,  12,  33,   2,   0,   0,   1,   1],
       [  2,  23,  30,   1,   9,  30,   1,   2,   0,   0,   4]],
      dtype=int64)

In [9]:
y=np.asanyarray(cdf['custcat'])
y[0:5]

array([1, 4, 3, 1, 3])

In [10]:
x=preprocessing.StandardScaler().fit(x).transform(x)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [14]:
l=LogisticRegression(C=0.01,solver='liblinear').fit(x_train,y_train)

In [15]:
yhat=l.predict(x_test)
yhat

array([4, 1, 3, 2, 1, 1, 2, 3, 1, 2, 1, 2, 4, 2, 4, 4, 3, 3, 3, 2, 3, 1,
       4, 3, 1, 3, 1, 1, 1, 1, 1, 1, 4, 2, 4, 3, 1, 3, 3, 3, 4, 1, 3, 3,
       4, 3, 4, 3, 1, 4, 3, 2, 2, 3, 1, 1, 3, 4, 3, 3, 1, 3, 4, 4, 2, 4,
       1, 4, 1, 1, 1, 3, 1, 3, 4, 3, 3, 3, 1, 4, 4, 1, 3, 3, 1, 4, 1, 1,
       2, 3, 3, 1, 1, 1, 1, 1, 3, 1, 4, 1, 1, 1, 1, 1, 1, 1, 2, 4, 4, 2,
       4, 4, 1, 1, 3, 2, 4, 3, 3, 1, 1, 4, 2, 2, 1, 4, 1, 2, 1, 1, 1, 1,
       1, 1, 4, 1, 3, 3, 2, 1, 1, 2, 3, 4, 3, 4, 3, 3, 4, 1, 2, 1, 4, 2,
       1, 4, 1, 3, 3, 3, 2, 4, 1, 3, 3, 3, 4, 3, 1, 1, 2, 1, 3, 1, 1, 3,
       3, 1, 1, 3, 3, 3, 4, 2, 3, 1, 1, 3, 1, 4, 2, 1, 2, 1, 4, 3, 2, 4,
       4, 3])

In [17]:
yhat_p=l.predict_proba(x_test)
yhat

array([4, 1, 3, 2, 1, 1, 2, 3, 1, 2, 1, 2, 4, 2, 4, 4, 3, 3, 3, 2, 3, 1,
       4, 3, 1, 3, 1, 1, 1, 1, 1, 1, 4, 2, 4, 3, 1, 3, 3, 3, 4, 1, 3, 3,
       4, 3, 4, 3, 1, 4, 3, 2, 2, 3, 1, 1, 3, 4, 3, 3, 1, 3, 4, 4, 2, 4,
       1, 4, 1, 1, 1, 3, 1, 3, 4, 3, 3, 3, 1, 4, 4, 1, 3, 3, 1, 4, 1, 1,
       2, 3, 3, 1, 1, 1, 1, 1, 3, 1, 4, 1, 1, 1, 1, 1, 1, 1, 2, 4, 4, 2,
       4, 4, 1, 1, 3, 2, 4, 3, 3, 1, 1, 4, 2, 2, 1, 4, 1, 2, 1, 1, 1, 1,
       1, 1, 4, 1, 3, 3, 2, 1, 1, 2, 3, 4, 3, 4, 3, 3, 4, 1, 2, 1, 4, 2,
       1, 4, 1, 3, 3, 3, 2, 4, 1, 3, 3, 3, 4, 3, 1, 1, 2, 1, 3, 1, 1, 3,
       3, 1, 1, 3, 3, 3, 4, 2, 3, 1, 1, 3, 1, 4, 2, 1, 2, 1, 4, 3, 2, 4,
       4, 3])

In [19]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test,yhat)

ValueError: Classification metrics can't handle a mix of continuous-multioutput and multiclass targets

In [21]:
from sklearn.metrics import log_loss
log_loss(y_test,yhat_p)

1.283797726717351