In [19]:
import itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [20]:
df=pd.read_csv("C:\\Users\\hp\\Desktop\\teleCust1000t.csv")
df.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9      64   4       5       0       0   
1       3      11   33        1        7     136   5       5       0       0   
2       3      68   52        1       24     116   1      29       0       1   
3       2      33   33        0       12      33   2       0       0       1   
4       2      23   30        1        9      30   1       2       0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [21]:
df['custcat'].value_counts()

3    281
1    266
4    236
2    217
Name: custcat, dtype: int64

In [22]:
df.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [23]:
x=df[['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside']].values
x[0:5]

array([[  2,  13,  44,   1,   9,  64,   4,   5,   0,   0,   2],
       [  3,  11,  33,   1,   7, 136,   5,   5,   0,   0,   6],
       [  3,  68,  52,   1,  24, 116,   1,  29,   0,   1,   2],
       [  2,  33,  33,   0,  12,  33,   2,   0,   0,   1,   1],
       [  2,  23,  30,   1,   9,  30,   1,   2,   0,   0,   4]],
      dtype=int64)

In [24]:
y=df['custcat'].values
y[0:5]

array([1, 4, 3, 1, 3], dtype=int64)

In [25]:
x=preprocessing.StandardScaler().fit(x).transform(x.astype(float))
x[0:5]

array([[-0.02696767, -1.055125  ,  0.18450456,  1.0100505 , -0.25303431,
        -0.12650641,  1.0877526 , -0.5941226 , -0.22207644, -1.03459817,
        -0.23065004],
       [ 1.19883553, -1.14880563, -0.69181243,  1.0100505 , -0.4514148 ,
         0.54644972,  1.9062271 , -0.5941226 , -0.22207644, -1.03459817,
         2.55666158],
       [ 1.19883553,  1.52109247,  0.82182601,  1.0100505 ,  1.23481934,
         0.35951747, -1.36767088,  1.78752803, -0.22207644,  0.96655883,
        -0.23065004],
       [-0.02696767, -0.11831864, -0.69181243, -0.9900495 ,  0.04453642,
        -0.41625141, -0.54919639, -1.09029981, -0.22207644,  0.96655883,
        -0.92747794],
       [-0.02696767, -0.58672182, -0.93080797,  1.0100505 , -0.25303431,
        -0.44429125, -1.36767088, -0.89182893, -0.22207644, -1.03459817,
         1.16300577]])

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [29]:
print('train set',x_train.shape,y_train.shape)

train set (800, 11) (800,)


In [30]:
print('train set',x_test.shape,y_test.shape)

train set (200, 11) (200,)


In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
k=4
n=KNeighborsClassifier(n_neighbors=k).fit(x_train,y_train)
n

KNeighborsClassifier(n_neighbors=4)

In [36]:
yhat=n.predict(x_test)
yhat[0:5]

array([1, 3, 2, 4, 1], dtype=int64)

In [38]:
from sklearn import metrics

In [39]:
print("train accuracy",metrics.accuracy_score(y_train,n.predict(x_train)))

train accuracy 0.56375


In [41]:
print("test accuracy",metrics.accuracy_score(y_test,yhat))

test accuracy 0.31


In [42]:
k=10
n=KNeighborsClassifier(n_neighbors=k).fit(x_train,y_train)
n

KNeighborsClassifier(n_neighbors=10)

In [43]:
yhat=n.predict(x_test)
yhat[0:5]

array([3, 3, 2, 4, 1], dtype=int64)

In [44]:
from sklearn import metrics

In [45]:
print("train accuracy",metrics.accuracy_score(y_train,n.predict(x_train)))

train accuracy 0.5075


In [46]:
print("test accuracy",metrics.accuracy_score(y_test,yhat))

test accuracy 0.305
